@HTML_REPORT_CONTENT
Feature: HTML Report Content Validation
  Validate that the HTML report generated by BehaveX contains the actual
  scenario content — including feature names, error messages for failing
  steps, and correct scenario counts — so that users can diagnose failures
  directly from the report without needing to inspect logs.

  Scenario: HTML report contains the feature name
    When I run the behavex command with a failing test
    Then I should see the generated HTML report contains the "Failing Test" string

  Scenario: HTML report contains the error message from a failing step
    When I run the behavex command with a failing test
    Then I should see the generated HTML report contains the "This step is designed to fail" string

  Scenario: HTML report contains all expected scenario statuses for a mixed run
    When I run the behavex command targeting the "xml_report_features/xml_validation_tests.feature" feature
    Then I should see the HTML report was generated and contains "5" scenarios

  Scenario: HTML report generated for passing tests contains no internal BehaveX variables
    When I run the behavex command with a passing test
    Then I should see the generated HTML report does not contain internal BehaveX variables and tags
