@XML_REPORT
Feature: JUnit XML Report Validation
  Validate that the JUnit XML report generated by BehaveX correctly reflects
  scenario outcomes with proper statuses, includes error details for failures,
  and expands Scenario Outline instances as individual testcase entries.

  Scenario: JUnit XML report files are generated
    When I run the behavex command targeting the "xml_report_features/xml_validation_tests.feature" feature
    Then I should see the JUnit XML report was generated

  Scenario Outline: Scenarios appear with correct status in the JUnit XML report
    When I run the behavex command targeting the "xml_report_features/xml_validation_tests.feature" feature
    Then I should see "<count>" scenarios with status "<status>" in the JUnit XML report
  Examples: expected status counts
    | count | status  |
    | 3     | passed  |
    | 1     | failed  |
    | 1     | skipped |

  Scenario: Failed scenarios include a failure element with error message content
    When I run the behavex command targeting the "xml_report_features/xml_validation_tests.feature" feature
    Then I should see error messages for failed scenarios in the JUnit XML report

  Scenario: Scenario Outline instances appear as individual entries in the JUnit XML report
    When I run the behavex command targeting the "xml_report_features/xml_validation_tests.feature" feature
    Then I should see the scenario name "alpha" in the JUnit XML report
    And I should see the scenario name "beta" in the JUnit XML report

  Scenario: JSON report scenario count matches the total number of executed scenarios
    When I run the behavex command targeting the "xml_report_features/xml_validation_tests.feature" feature
    Then I should see "5" scenarios in the JSON report

  Scenario: HTML and JUnit XML reports contain the same total number of scenarios
    When I run the behavex command targeting the "xml_report_features/xml_validation_tests.feature" feature
    Then I should see the same number of scenarios in the reports
