---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: check-added-large-files
      - id: check-json
      - id: double-quote-string-fixer
      - id: fix-encoding-pragma
      - id: file-contents-sorter
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
        args: [--branch, develop, --branch, master]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [--skip, "B101,B307,B322"]  # ignore assert_used

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.9'
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-bugbear==19.8.0',
            'flake8-coding==1.3.2',
            'flake8-comprehensions==3.0.1',
            'flake8-debugger==3.2.1',
            'flake8-deprecated==1.3',
            #'flake8-docstrings==1.5.0',
            'flake8-pep3101==1.2.1',
            'flake8-polyfill==1.0.2',
            #'flake8-print==3.1.4',
            #'flake8-quotes==2.1.1',
            'flake8-string-format==0.2.3',
        ]

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--skip-string-normalization]
        language_version: python3.8

  # - repo: https://github.com/PyCQA/pylint
  #   rev: pylint-2.6.0
  #   hooks:
  #     - id: pylint
  #       args:
  #         - --max-line-length=120
  #         - --ignore-imports=yes
  #         - -d duplicate-code
