version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      - pip install --upgrade pip setuptools
    post_install:
      - pip install -e .
