version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
